language: cpp

compiler:
    - gcc

dist: xenial

before_install:
    - sudo apt-get install zlib1g-dev libmxml-dev libfftw3-dev dssi-dev libfltk1.3-dev libxpm-dev
    - sudo apt-get install --force-yes cxxtest
    - wget http://downloads.sourceforge.net/liblo/liblo-0.28.tar.gz
    - tar xvf liblo-0.28.tar.gz && cd liblo-0.28
    - ./configure && make && sudo make install
    - sudo ldconfig
    - cd ..


script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest --output-on-failure
